baseURL = "https://wunderwuzzi23.github.io/blog/"
languageCode = "en-us"
title = "wunderwuzzi blog"
theme = "vienna"
copyright = "&copy; WUNDERWUZZI 2019"
publishDir = "docs"

[params]
subtitle = "Embrace the Red"
github = "wunderwuzzi23"
contact = "mailto:security@wunderwuzzi.net"
